version: '3.5'

services:
  mysqlsrv:
    container_name: ${DATABASE_PROD_ENV}
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      #- /volumes_containers/proj_biblia/vol_mysql:/var/lib/mysql/
      - ${VOLUME_DATABASE}:/var/lib/mysql
      - ${VOLUME_DATABASE_SQL}:/docker-entrypoint-initdb.d/biblias13v.sql
      #arquivos com extensões .sh, .sqle .sql.gzque são que encontrados em /docker-entrypoint-initdb.d dentro do container são executados
      # automaticamente pelo proprio mysql em ordem alfabética..
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: "biblias13v"
    restart: always
    ports:
      - ${PORTS_MYSQL}
    networks:
      network-mysql-nodejs:
        ipv4_address: ${IP_ADDRESS_MYSQL}

  nodeapi:
    image: "node:16"
    container_name: ${NODEAPI_PROD_ENV}
    working_dir: ${WORK_DIR}
    environment:
      - NODE_env=production
    user: node
    ports:
      - ${PORTS_NODE}
    restart: always
    depends_on:
      - mysqlsrv
    volumes:
      - ${VOLUME_NODE_APP}
      - ${VOLUME_NODE_LOGS}
    command: ${NODE_PROD_START}
    networks:
      network-mysql-nodejs:
        ipv4_address: ${IP_ADDRESS_NODE}

  nodenext:
    image: "node:16"
    container_name: ${NODENEXT_PROD_ENV}
    user: node
    working_dir: ${WORK_DIR_NEXT}
    environment:
      - NODE_env=production
    ports:
      - ${PORTS_NODE_NEXT}
    restart: always
    depends_on:
      - nodeapi
    volumes:
      - ${VOLUME_NEXT_APP}
    command: ${NODE_NEXT_PROD_START}
    networks:
      network-mysql-nodejs:
        ipv4_address: ${IP_ADDRESS_NODE_NEXT}

  nginxnext:
    image: nginx
    container_name: ${NGINX_PROD_ENV}
    volumes:
      # - ${VOLUME_SITE}
      - ${VOLUME_SSL_CRT}
      - ${VOLUME_SSL_KEY}
      - ${VOLUME_DEFAULT_CONF}
    ports:
      - ${PORTS_NGINX}
      - ${PORTS_NGINX_SSL}
    restart: always
    depends_on:
      - nodeapi
    networks:
      network-mysql-nodejs:
        ipv4_address: ${IP_ADDRESS_NGINX}

networks:
  network-mysql-nodejs:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK}
          # gateway: 172.29.0.1

          #-----------------------------------------------------------------------------------------------------------------------
          #!/bin/sh

          # Esse é o script --script_mysql.sh-- executado na linha 19

          # mysql -u root -pdeusepoder --execute="CREATE USER 'docker_biblia'@'localhost' IDENTIFIED BY 'M@deld4166'; GRANT ALL PRIVILEGES ON * . * TO 'docker_biblia'@'localhost'; UPDATE mysql.user SET host='%' WHERE user='docker_biblia'; FLUSH PRIVILEGES;"

          # CREATE USER 'docker_biblia'@'localhost' IDENTIFIED BY 'M@deld4166';
          # linha acima: cria usuario com a senha M@...

          # GRANT ALL PRIVILEGES ON * . * TO 'docker_biblia'@'localhost';
          # linha acima: add privilégios em todas as tabelas

          # UPDATE mysql.user SET host="%" WHERE user="docker_biblia";
          # linha acima: conf o servidor para permitir acesso pelo user de qualquer origem

          # FLUSH PRIVILEGES;
          # linha acima:  reload dos privégios

          #-----------------------------------------------------------------------------------------------------------------------
