import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import NavBar from "../components/navbar"
import Footer from "../components/footer"
import ArticleHome from '../components/articleHomeInfos'
import { IProps, IresultTestamento, IresultVersao } from '@/entities/interfaces'
import { FetchAPITestamentoServerSide, FetchAPIVersaoServerSide } from '@/services/fetch'



export default function Home({ preRenderVersaoOpcoes, preRenderTestamentoOpcoes }: IProps) {
  return (
    <>
      <div className={styles.backgroundanimation}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <NavBar preRenderVersaoOpcoes={preRenderVersaoOpcoes} preRenderTestamentoOpcoes={preRenderTestamentoOpcoes} />
        <ArticleHome />
      </div>
      <Footer />
    </>
  )
}


export async function getServerSideProps() {
  let preRenderVersaoOpcoes: IresultVersao[] = await FetchAPIVersaoServerSide()
  let preRenderTestamentoOpcoes: IresultTestamento[] = await FetchAPITestamentoServerSide()
  // Fetch data from external API on time build
  return { props: { preRenderVersaoOpcoes, preRenderTestamentoOpcoes } }
}

