name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_VPS }}
        username: ${{ secrets.USER_VPS }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          sudo bash /bibliaSiteFromGitHub/biblia-nextjs/GitHubPull.sh
          sudo cp /volDockerEnvEnviroment/composeEnv/.env /bibliaSiteFromGitHub/biblia-nextjs/
          sudo cp /volDockerEnvEnviroment/nodeEnv/.env /bibliaSiteFromGitHub/biblia-nextjs/server/
