name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_VPS }}
        username: ${{ secrets.USER_VPS }}
        key: ${{ secrets.PASSWORD }}
        port: 22
        script: ls
        
        
